version: '3.8'

services:
  genetic-algorithm-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ga_app
    environment:
      DISPLAY: "host.docker.internal:0.0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: "host"
    stdin_open: true
    tty: true
